In [1]:
my_list = [1, 2, 3]
new_list = [x * 2 for x in my_list]
print(new_list)

[2, 4, 6]


In [3]:
import numpy as np
my_array = np.array([1, 2, 3])
new_array = my_array * 2
print(new_array)

[2 4 6]


In [4]:
array = np.array([2, 4, 6])
add = array + 10
print(add)

[12 14 16]


In [ ]:
# 시작, 종료, N단계
arr = np.arange(0, 10, 2)
print(arr)

[0 2 4 6 8]


In [ ]:
# 3행 3열 모양 : 균일 분포 따르는 난수표 생성
arr = np.random.rand(3,3)
print(arr)

[[0.19172738 0.49659875 0.01893532]
 [0.18612069 0.17105524 0.18558142]
 [0.46796845 0.40695214 0.83786059]]


In [ ]:
# 배열 모양 변경
arr = arr.reshape(1,9)
print(arr)

[[0.19172738 0.49659875 0.01893532 0.18612069 0.17105524 0.18558142
  0.46796845 0.40695214 0.83786059]]


In [ ]:
npsum = np.sum([1,2,3])
print(npsum)

In [10]:
mean = np.mean([1,2,3])
print(mean)

2.0


In [11]:
#표준편차
std = np.std([175, 177, 179, 181, 183])
print(std)

2.8284271247461903


In [14]:
data = np.array = ([1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9])
add = np.sum(data)
print(add)

45


In [ ]:
# 가로로
row_sum = np.sum(data, axis=1)
print(" 각 행의 합 : ", row_sum)

 각 행의 합 :  [ 6 15 24]


In [ ]:
# 세로
row_sum = np.sum(data, axis=0)
print(" 각 행의 합 : ", row_sum)

 각 행의 합 :  [12 15 18]


In [ ]:
mean_all = np.mean(data)
print(mean_all)
# 45 / 9 

5.0


In [25]:
mean_row = np.mean(data, axis=1)
print(mean_row)

[2. 5. 8.]


In [26]:
mean_row = np.mean(data, axis=0)
print(mean_row)

[4. 5. 6.]


In [27]:
mean_row = np.std(data, axis=0)
print(mean_row)

[2.44948974 2.44948974 2.44948974]


In [28]:
mean_row = np.mean(data, axis=1)
print(mean_row)

[2. 5. 8.]
