In [ ]:
# Numpy 벡터화 연산과 비교하기 위한 list 예제
my_list = [1, 2, 3]
new_list = [x * 2 for x in my_list]
print(new_list)

[2, 4, 6]


In [ ]:
# 벡터화 연산 예제(1): 배열의 각 요소에 대해 반복문 없이 한 번에 연산 수행하는 방식
# 사전설치 : pip install numpy
import numpy as np
my_array = np.array([1, 2, 3])
new_array = my_array * 2
print(new_array)

[2 4 6]


In [4]:
array = np.array([2, 4, 6])
add = array + 10
print(add)

[12 14 16]


In [ ]:
# 벡터화 연산 예제(2)
arr = np.array([1, 2, 3, 4, 5])  # NumPy 배열 생성
result = arr + 10  # 모든 요소에 10을 더하기
print(result)

In [ ]:
# 시작, 종료, N단계
arr = np.arange(0, 10, 2)
print(arr)

[0 2 4 6 8]


In [ ]:
# 3행 3열 모양 : 균일 분포 따르는 난수표 생성
arr = np.random.rand(3,3)
print(arr)

[[0.19172738 0.49659875 0.01893532]
 [0.18612069 0.17105524 0.18558142]
 [0.46796845 0.40695214 0.83786059]]


In [ ]:
# 배열 모양 변경
arr = arr.reshape(1,9)
print(arr)

[[0.19172738 0.49659875 0.01893532 0.18612069 0.17105524 0.18558142
  0.46796845 0.40695214 0.83786059]]


In [ ]:
npsum = np.sum([1,2,3])
print(npsum)

In [10]:
mean = np.mean([1,2,3])
print(mean)

2.0


In [11]:
#표준편차
std = np.std([175, 177, 179, 181, 183])
print(std)

2.8284271247461903


In [ ]:
import numpy as np
# 1부터 10까지의 숫자를 가진 배열 생성
data = np.arange(1, 11)
print(data)

In [ ]:
# 2차원 배열 생성
data = np.array = ([1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9])
add = np.sum(data)
print(add)

45


In [ ]:
# 합 계산
sum_data = np.sum(data)
print("합:", sum_data)

# 평균 계산
mean_data = np.mean(data)
print("평균:", mean_data)

# 표준편차 계산
std_data = np.std(data)
print("표준편차:", std_data)

In [ ]:
# 가로로
row_sum = np.sum(data, axis=1)
print(" 각 행의 합 : ", row_sum)

 각 행의 합 :  [ 6 15 24]


In [ ]:
# 세로
row_sum = np.sum(data, axis=0)
print(" 각 행의 합 : ", row_sum)

 각 행의 합 :  [12 15 18]


In [ ]:
mean_all = np.mean(data)
print(mean_all)
# 45 / 9 

5.0


In [ ]:
# 각 행의 평균
mean_row = np.mean(data, axis=1)
print(mean_row)

[2. 5. 8.]


In [ ]:
# 각 열의 평균
mean_row = np.mean(data, axis=0)
print(mean_row)

[4. 5. 6.]


In [ ]:
# 전체 요소의 표준편차
std_all = np.std(data)
print("전체 요소의 표준편차:", std_all)

In [ ]:
# 각 열의 표준편차
mean_row = np.std(data, axis=0)
print(mean_row)

[2.44948974 2.44948974 2.44948974]


In [ ]:
# 각 행의 표준편차
mean_row = np.mean(data, axis=1)
print(mean_row)

[2. 5. 8.]


In [ ]:
# 1차원 배열 생성
arr1 = np.array([1, 2, 3, 4, 5])
# 2차원 배열 생성
arr2 = np.array([[1, 2, 3],
                [4, 5, 6]])

In [ ]:
# 배열의 shape 확인
print(arr2.shape)

In [ ]:
# 특정 요소에 접근
print(arr2[1, 2])   # 두 번째 행, 세 번째 열

# 슬라이싱
print(arr2[:, 1])  # 모든 행의 두 번째 열

# 특정 요소에 접근
print(arr2[0][1])  # 첫 번째 행의 두 번째 요소(특정 위치의 값을 가져올 때)